// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXRpqZvJx7wWDIk1D9FYkM2DZLhqsxuLg',
    appId: '1:1089074479286:web:136f856bcb9c315e7d6617',
    messagingSenderId: '1089074479286',
    projectId: 'noteapp-7f720',
    authDomain: 'noteapp-7f720.firebaseapp.com',
    storageBucket: 'noteapp-7f720.appspot.com',
    measurementId: 'G-J19ZY0VZ9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJmkk6QF5UkYr21ApXOBOOFdvUzt1PQQ',
    appId: '1:1089074479286:android:6983d076d2f436ab7d6617',
    messagingSenderId: '1089074479286',
    projectId: 'noteapp-7f720',
    storageBucket: 'noteapp-7f720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VgNQmykk1GGZQtdMH52dg_I5GSMArUY',
    appId: '1:1089074479286:ios:6ae8f80a97139a407d6617',
    messagingSenderId: '1089074479286',
    projectId: 'noteapp-7f720',
    storageBucket: 'noteapp-7f720.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1VgNQmykk1GGZQtdMH52dg_I5GSMArUY',
    appId: '1:1089074479286:ios:6ae8f80a97139a407d6617',
    messagingSenderId: '1089074479286',
    projectId: 'noteapp-7f720',
    storageBucket: 'noteapp-7f720.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXRpqZvJx7wWDIk1D9FYkM2DZLhqsxuLg',
    appId: '1:1089074479286:web:dfcd9363cc6e02fb7d6617',
    messagingSenderId: '1089074479286',
    projectId: 'noteapp-7f720',
    authDomain: 'noteapp-7f720.firebaseapp.com',
    storageBucket: 'noteapp-7f720.appspot.com',
    measurementId: 'G-THM809CYBV',
  );
}
